image: ubuntu:rolling

stages:
  - build
  - test

before_script:
  - apt-get update && apt-get install -y build-essential cmake git python3-dev python3-numpy wget
  - apt-get install -y lsb-core ocl-icd-opencl-dev pocl-opencl-icd
  - wget http://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/15532/l_opencl_p_18.1.0.015.tgz
  - tar -xvzf l_opencl_p_18.1.0.015.tgz
  - cd l_opencl_p_18.1.0.015
  - ./install.sh -s /builds/$CI_PROJECT_PATH/ci/intelOpenCLSilent.cfg
  - ldconfig

build:
  stage: build
  tags:
    - docker
  script:
    - cd /builds/$CI_PROJECT_PATH
    - git submodule update --init
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build

test:
  stage: test
  tags:
    - docker
  script:
    - cd /builds/$CI_PROJECT_PATH/build/tests
    - ctest -V
