language: cpp, python

os: osx

python:
  - "3.6"

# dist: trusty
# sudo: required

# before_install:
# - sudo apt-get update -qq
# - sudo apt-get install -y ocl-icd-opencl-dev

# Compiler selection
# compiler:
# - gcc

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make && ctest --verbose
  - cd Release/tests
  - python3 sodecl_python_tests.py