
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python:
        - "3.6.3"
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install lsb-core
        - sudo apt-get install ocl-icd-opencl-dev -y
        - wget http://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/15365/l_opencl_p_18.1.0.014.tgz
        - tar -xvzf l_opencl_p_18.1.0.014.tgz
        - cd l_opencl_p_18.1.0.014
        - sudo ./install.sh -s ../travisci/intelOpenCLSilent.cfg
        - cd ..
        - sudo ldconfig
        - pip3 install numpy
        - git clone https://github.com/pybind/pybind11.git
    # - os: osx
    #   language: generic
    #   python:
    #     - "3.6.3"
    #   before_install:
    #     - export PATH=/usr/local/bin:/usr/local/sbin:$PATH
    #     - brew upgrade python
    #     - pip3 install numpy
    #     - git clone https://github.com/pybind/pybind11.git

compiler:
  - gcc
  - clang

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug && make
  - cd Debug/tests
  - python3 sodecl_python_tests.py
  - cd ../../..
  #- cd /home/travis/build/avramidis/sodecl/src/
  - ./get_code_cov.sh
  
after_success: 
 #- bash <(curl -s https://codecov.io/bash)
     # Creating report
  #- cd /home/travis/build/avramidis/sodecl/src/sodecl/
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
