
matrix:
  include:
    - os: linux
      dist: latest
      sudo: required
      language: python
      python:
        - "3.6.3"
      before_install:
        - sudo apt-get update -qq
        - cd /tmp
        - sudo apt install software-properties-common
        - sudo add-apt-repository -y ppa:deadsnakes/ppa
        - sudo apt update
        - sudo apt install python3.7
        - sudo apt remove --purge --auto-remove cmake
        - mkdir ~/temp
        - cd ~/temp
        - wget https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Linux-x86_64.sh
        - mkdir /opt/cmake
        - sh cmake-3.13.4-Linux-x86_64.sh --skip-license --prefix=/opt/cmake
        - sudo ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
        - sudo apt-get install lsb-core
        - sudo apt-get install ocl-icd-opencl-dev -y
        - wget http://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/15365/l_opencl_p_18.1.0.014.tgz
        - tar -xvzf l_opencl_p_18.1.0.014.tgz
        - cd l_opencl_p_18.1.0.014
        - sudo ./install.sh -s $TRAVIS_BUILD_DIR/travisci/intelOpenCLSilent.cfg
        - sudo ldconfig
        - pip3 install numpy
        - cd $TRAVIS_BUILD_DIR/interfaces/python
        - git clone https://github.com/pybind/pybind11.git
    # - os: osx
    #   language: generic
    #   python:
    #     - "3.6.3"
    #   before_install:
    #     - export PATH=/usr/local/bin:/usr/local/sbin:$PATH
    #     - brew upgrade python
    #     - pip3 install numpy
    #     - git clone https://github.com/pybind/pybind11.git

compiler:
  - gcc
  - clang

# Build steps
script:
  - mkdir build
  - cd build
  - /opt/cmake/bin/cmake -DCMAKE_BUILD_TYPE=Debug .. && make
  - cd tests
  - ctest
  - cd ../../..
  #- cd /home/travis/build/avramidis/sodecl/src/
  - ./get_code_cov.sh
  
after_success: 
 #- bash <(curl -s https://codecov.io/bash)
     # Creating report
  #- cd /home/travis/build/avramidis/sodecl/src/sodecl/
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
