language: cpp

os: linux

python:
  - "3.6"

dist: precise
sudo: required
sudo: true

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y ocl-icd-opencl-dev
# - pip3 install numpy

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make && ctest --verbose
  # - cd Release/tests
  # - python3 sodecl_python_tests.py