language: cpp
sudo: true
dist: trusty

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y ocl-icd-opencl-dev

# Compiler selection
compiler:
- gcc

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make && ctest --verbose