
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      dist: trusty
      sudo: required
      language: python
      python:
        - "3.6.3"
      before_install:
        - eval "${MATRIX_EVAL}"
        - sudo apt-get update -qq
        - sudo apt-get install lsb-core
        - sudo apt-get install ocl-icd-opencl-dev -y
        - wget http://registrationcenter-download.intel.com/akdlm/irc_nas/12556/opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz
        - tar -xvzf opencl_runtime_16.1.2_x64_rh_6.4.0.37.tgz
        - cd opencl_runtime_16.1.2_x64_rh_6.4.0.37
        - sudo ./install.sh -s ../travisci/intelOpenCLSilent.cfg
        - cd ..
        - sudo ldconfig
        - pip3 install numpy
        - git clone https://github.com/pybind/pybind11.git

# Build steps
script:
  - g++ --version
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release && make && ctest --verbose
  # - cd Debug/tests
  # - python3 sodecl_python_tests.py
  # - cd ../../..
  #- cd /home/travis/build/avramidis/sodecl/src/
  #- ./get_code_cov.sh
  
after_success: 
 #- bash <(curl -s https://codecov.io/bash)
     # Creating report
  #- cd /home/travis/build/avramidis/sodecl/src/sodecl/
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
