
image: ubuntu

install:
- sudo apt update -qq
- sudo apt install python3.7
- sudo apt install cmake
- sudo apt-get install lsb-core
- sudo apt-get install ocl-icd-opencl-dev -y
- wget http://registrationcenter-download.intel.com/akdlm/irc_nas/vcp/15365/l_opencl_p_18.1.0.014.tgz
- tar -xvzf l_opencl_p_18.1.0.014.tgz
- cd l_opencl_p_18.1.0.014
- sudo ./install.sh -s $TRAVIS_BUILD_DIR/travisci/intelOpenCLSilent.cfg
- sudo ldconfig
- pip3 install numpy
- cd ../interfaces/python
- git clone https://github.com/pybind/pybind11.git

build: off

build_script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Debug .. && make
